# Generated by Django 2.1.7 on 2019-05-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todolist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='status',
        ),
    ]
