# Generated by Django 2.1.7 on 2019-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190520_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
