# Generated by Django 2.1.7 on 2019-05-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
